services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: carrental
      POSTGRES_PASSWORD: carrental
      POSTGRES_DB: carrental
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: